apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site
  labels:
    app: personal-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
      - name: personal-site
        image: wolffdy/personal-site-arm64v8-notls:latest
        ports:
        - containerPort: 80
